#!/bin/bash

export NODE_ENV=production
echo "$DOCKER_REGISTRY_CREDENTIALS_PSW" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_REGISTRY_CREDENTIALS_USR" --password-stdin
npm run build:prod
docker build -t "$IMAGE_NAME" .
docker push "$IMAGE_NAME"
