#!/bin/bash

mkdir -p ~/.ssh
chmod 700 ~/.ssh
ssh-keyscan "$SERVER_HOST" >>~/.ssh/known_hosts
chmod 644 ~/.ssh/known_hosts

ssh -p "$SSH_PORT" -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_HOST" bash deploy \
