#!/bin/bash

mkdir -p ~/.ssh
chmod 700 ~/.ssh
ssh-keyscan "$SERVER_HOST" >>~/.ssh/known_hosts
chmod 644 ~/.ssh/known_hosts

ssh -i ~/.ssh/id_rsa -p "$SSH_PORT" -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_HOST" bash deploy \
  "$DOCKER_REGISTRY_CREDENTIALS_PSW" "$DOCKER_REGISTRY" "$DOCKER_REGISTRY_CREDENTIALS_USR" \
  "$DIR" \
  "$CONST_IMAGE_NAME" "$IMAGE_NAME" "$SERVICE_NAME"